### ISSUE TITLE
Use concourse caches with terraform?

### ISSUE THREAD

**Issue by itsdalmo** [TeliaSoneraNorge/divx-concourse-tasks#4]
This should reduce build times for terraform tasks:

```
caches:
- path: source/$directory/.terraform
```

Requires setting `-update=true` on init and get as well.

**Comment by itsdalmo** [comment]
This is already implemented. `cache: true` in params for the task will store `.terraform` for all `directories: `, and load them if the cache already exists. However, `-update=true` seems to always replace the modules, which invalidates the point of having a cache. Should do some more experimentation on this.

**Comment by mikael-lindstrom** [comment]
Kind of make sense, so either we have `-update=true` or `cache: true`?

**Comment by itsdalmo** [comment]
I tested `terraform get -update=true`, and it does not appear to re-download modules which are found in the cache. So, in combination with `terraform init` it should yield the correct version of providers and modules (even if they have changed between whats cached and the code).
